# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Gui\ui_files\MainWindow.ui'
#
# Created by: PySide2 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 621)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 11, 821, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_senderName = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_senderName.sizePolicy().hasHeightForWidth())
        self.label_senderName.setSizePolicy(sizePolicy)
        self.label_senderName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_senderName.setObjectName("label_senderName")
        self.gridLayout.addWidget(self.label_senderName, 1, 3, 1, 1)
        self.label_boxes = QtWidgets.QLabel(self.layoutWidget)
        self.label_boxes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_boxes.setTextFormat(QtCore.Qt.PlainText)
        self.label_boxes.setObjectName("label_boxes")
        self.gridLayout.addWidget(self.label_boxes, 2, 6, 1, 1)
        self.lineEdit_consNum = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_consNum.sizePolicy().hasHeightForWidth())
        self.lineEdit_consNum.setSizePolicy(sizePolicy)
        self.lineEdit_consNum.setObjectName("lineEdit_consNum")
        self.gridLayout.addWidget(self.lineEdit_consNum, 0, 2, 1, 1)
        self.label_consCode = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_consCode.sizePolicy().hasHeightForWidth())
        self.label_consCode.setSizePolicy(sizePolicy)
        self.label_consCode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_consCode.setObjectName("label_consCode")
        self.gridLayout.addWidget(self.label_consCode, 0, 1, 1, 1)
        self.textEdit_eMail = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.textEdit_eMail.sizePolicy().hasHeightForWidth())
        self.textEdit_eMail.setSizePolicy(sizePolicy)
        self.textEdit_eMail.setObjectName("textEdit_eMail")
        self.gridLayout.addWidget(self.textEdit_eMail, 4, 0, 1, 10)
        self.lcdNumber_boxes = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_boxes.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_boxes.setObjectName("lcdNumber_boxes")
        self.gridLayout.addWidget(self.lcdNumber_boxes, 2, 7, 2, 3)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 5, 9, 1, 1)
        self.label_voucher = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_voucher.sizePolicy().hasHeightForWidth())
        self.label_voucher.setSizePolicy(sizePolicy)
        self.label_voucher.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_voucher.setTextFormat(QtCore.Qt.PlainText)
        self.label_voucher.setObjectName("label_voucher")
        self.gridLayout.addWidget(self.label_voucher, 2, 0, 1, 1)
        self.label_consNum = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_consNum.sizePolicy().hasHeightForWidth())
        self.label_consNum.setSizePolicy(sizePolicy)
        self.label_consNum.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_consNum.setTextFormat(QtCore.Qt.PlainText)
        self.label_consNum.setObjectName("label_consNum")
        self.gridLayout.addWidget(self.label_consNum, 0, 0, 1, 1)
        self.comboBox_recievingStore = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_recievingStore.sizePolicy().hasHeightForWidth())
        self.comboBox_recievingStore.setSizePolicy(sizePolicy)
        self.comboBox_recievingStore.setObjectName("comboBox_recievingStore")
        self.gridLayout.addWidget(self.comboBox_recievingStore, 0, 4, 1, 4)
        self.pushButton_send = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 5, 8, 1, 1)
        self.tableWidget_voucher = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_voucher.sizePolicy().hasHeightForWidth())
        self.tableWidget_voucher.setSizePolicy(sizePolicy)
        self.tableWidget_voucher.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget_voucher.setObjectName("tableWidget_voucher")
        self.tableWidget_voucher.setColumnCount(0)
        self.tableWidget_voucher.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_voucher, 3, 0, 1, 6)
        self.dateTimeEdit_date = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_date.setObjectName("dateTimeEdit_date")
        self.gridLayout.addWidget(self.dateTimeEdit_date, 0, 9, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 3, 6, 1, 1)
        self.lineEdit_senderName = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_senderName.sizePolicy().hasHeightForWidth())
        self.lineEdit_senderName.setSizePolicy(sizePolicy)
        self.lineEdit_senderName.setObjectName("lineEdit_senderName")
        self.gridLayout.addWidget(self.lineEdit_senderName, 1, 4, 1, 3)
        self.label_date = QtWidgets.QLabel(self.layoutWidget)
        self.label_date.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_date.setObjectName("label_date")
        self.gridLayout.addWidget(self.label_date, 0, 8, 1, 1)
        self.label_recievingStore = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_recievingStore.sizePolicy().hasHeightForWidth())
        self.label_recievingStore.setSizePolicy(sizePolicy)
        self.label_recievingStore.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_recievingStore.setObjectName("label_recievingStore")
        self.gridLayout.addWidget(self.label_recievingStore, 0, 3, 1, 1)
        self.lineEdit_voucher = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_voucher.sizePolicy().hasHeightForWidth())
        self.lineEdit_voucher.setSizePolicy(sizePolicy)
        self.lineEdit_voucher.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_voucher.setObjectName("lineEdit_voucher")
        self.gridLayout.addWidget(self.lineEdit_voucher, 2, 1, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInstructions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Συνέπειες"))
        self.label_senderName.setText(_translate("MainWindow", "Ονοματεπώνυμο Αποστολέα:"))
        self.label_boxes.setText(_translate("MainWindow", "Σύνολο Κιβωτίων:"))
        self.label_consCode.setText(_translate("MainWindow", "27TA09-"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_voucher.setText(_translate("MainWindow", "Voucher:"))
        self.label_consNum.setText(_translate("MainWindow", "Αριθμός Δελτίου:"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.pushButton_delete.setText(_translate("MainWindow", "Διαγραφή"))
        self.label_date.setText(_translate("MainWindow", "Ημερομηνία:"))
        self.label_recievingStore.setText(_translate("MainWindow", "Κατάστημα Αποστολής:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
