# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Gui\ui_files\MainWindow.ui'
#
# Created by: PySide2 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 621)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 11, 821, 541))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_hmeromhnia = QtWidgets.QLabel(self.widget)
        self.label_hmeromhnia.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_hmeromhnia.setObjectName("label_hmeromhnia")
        self.gridLayout.addWidget(self.label_hmeromhnia, 0, 8, 1, 1)
        self.label_arithmosDeltiou = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arithmosDeltiou.sizePolicy().hasHeightForWidth())
        self.label_arithmosDeltiou.setSizePolicy(sizePolicy)
        self.label_arithmosDeltiou.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_arithmosDeltiou.setTextFormat(QtCore.Qt.PlainText)
        self.label_arithmosDeltiou.setObjectName("label_arithmosDeltiou")
        self.gridLayout.addWidget(self.label_arithmosDeltiou, 0, 0, 1, 1)
        self.label_kwdikosDeltiou = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_kwdikosDeltiou.sizePolicy().hasHeightForWidth())
        self.label_kwdikosDeltiou.setSizePolicy(sizePolicy)
        self.label_kwdikosDeltiou.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_kwdikosDeltiou.setObjectName("label_kwdikosDeltiou")
        self.gridLayout.addWidget(self.label_kwdikosDeltiou, 0, 1, 1, 1)
        self.lineEdit_voucher = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_voucher.sizePolicy().hasHeightForWidth())
        self.lineEdit_voucher.setSizePolicy(sizePolicy)
        self.lineEdit_voucher.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lineEdit_voucher.setObjectName("lineEdit_voucher")
        self.gridLayout.addWidget(self.lineEdit_voucher, 1, 1, 1, 4)
        self.lcdNumber_kivwtia = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_kivwtia.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_kivwtia.setObjectName("lcdNumber_kivwtia")
        self.gridLayout.addWidget(self.lcdNumber_kivwtia, 1, 7, 2, 3)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 4, 1, 4)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 4, 9, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 0, 1, 10)
        self.label_voucher = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_voucher.sizePolicy().hasHeightForWidth())
        self.label_voucher.setSizePolicy(sizePolicy)
        self.label_voucher.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_voucher.setTextFormat(QtCore.Qt.PlainText)
        self.label_voucher.setObjectName("label_voucher")
        self.gridLayout.addWidget(self.label_voucher, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_katasthma = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_katasthma.sizePolicy().hasHeightForWidth())
        self.label_katasthma.setSizePolicy(sizePolicy)
        self.label_katasthma.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_katasthma.setObjectName("label_katasthma")
        self.gridLayout.addWidget(self.label_katasthma, 0, 3, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.widget)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 4, 8, 1, 1)
        self.tableWidget_voucher = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_voucher.sizePolicy().hasHeightForWidth())
        self.tableWidget_voucher.setSizePolicy(sizePolicy)
        self.tableWidget_voucher.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget_voucher.setObjectName("tableWidget_voucher")
        self.tableWidget_voucher.setColumnCount(0)
        self.tableWidget_voucher.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_voucher, 2, 0, 1, 6)
        self.label_kivwtia = QtWidgets.QLabel(self.widget)
        self.label_kivwtia.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_kivwtia.setTextFormat(QtCore.Qt.PlainText)
        self.label_kivwtia.setObjectName("label_kivwtia")
        self.gridLayout.addWidget(self.label_kivwtia, 1, 6, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 0, 9, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Συνέπειες"))
        self.label_hmeromhnia.setText(_translate("MainWindow", "Ημερομηνία:"))
        self.label_arithmosDeltiou.setText(_translate("MainWindow", "Αριθμός Δελτίου:"))
        self.label_kwdikosDeltiou.setText(_translate("MainWindow", "27TA09-"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_voucher.setText(_translate("MainWindow", "Voucher:"))
        self.label_katasthma.setText(_translate("MainWindow", "Κατάστημα:"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.label_kivwtia.setText(_translate("MainWindow", "Σύνολο Κιβωτίων:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
